sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2

branches:
  only:
    - jekyll
script:
  - git clone -b master --depth 1 "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" _site
  - rm -rf _site/*
  - bundle install
  - bundle exec jekyll build
after_success:
  - cd _site
  - git add -A
  - git commit -m "Travis build $(git rev-parse --short $TRAVIS_COMMIT)"
  - git push "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master
