
# SEO settings
title: "Jeong"
title2: "Arm" # default: ""
description: "Just blogging!"
keywords: "Engineering, Music, Think"
url: https://kjwon15.github.io
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/kjwon15/kjwon15.github.io
disqus_shortname: "kjwon15-github"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jeong Arm"
  job      : "Software Engineer"
  bio      : "My name is Jeong Arm (Pronounced as Jeong Ah-reum)."
  thumb    : /images/author.jpg
  email    : kjwonmail@gmail.com
  url      : http://kjwon15.github.io
  github   : http://github.com/kjwon15

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@kjwon15"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: 
  - thinkspace/
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"

plugins_dir: thinkspace/_plugins/
layouts_dir: thinkspace/_layouts/
includes_dir: thinkspace/_includes/

